### PR TITLE
Permission deconstruction

### PR DESCRIPTION
**Pull request by zprebosnyak-lm**
### Description

Frontend changes in [PR 103](https://github.com/DependencyTrack/hyades-frontend/pull/103)

This PR breaks down the current permissions set to align with the CRUD operations that each permission can perform through the API. It retains the original permissions to stay backwards compatible. The original permissions are a top level permission that can perform all the CRUD operations the broken down permissions can.

Updated permission set:
```java
BOM_UPLOAD("Allows the ability to upload CycloneDX Software Bill of Materials (SBOM)"),
VIEW_PORTFOLIO("Provides the ability to view the portfolio of projects, components, and licenses"),
PORTFOLIO_MANAGEMENT("Allows the creation, modification, and deletion of data in the portfolio"),
PORTFOLIO_MANAGEMENT_CREATE("Allows the creation of data in the portfolio"),
PORTFOLIO_MANAGEMENT_READ("Allows the reading of data in the portfolio"),
PORTFOLIO_MANAGEMENT_UPDATE("Allows the updating of data in the portfolio"),
PORTFOLIO_MANAGEMENT_DELETE("Allows the deletion of data in the portfolio"),
VIEW_VULNERABILITY("Provides the ability to view the vulnerabilities projects are affected by"),
VULNERABILITY_ANALYSIS("Provides all abilities to make analysis decisions on vulnerabilities"),
VULNERABILITY_ANALYSIS_CREATE("Provides the ability to upload supported VEX documents to a project"),
VULNERABILITY_ANALYSIS_READ("Provides the ability read the VEX document for a project"),
VULNERABILITY_ANALYSIS_UPDATE("Provides the ability to make analysis decisions on vulnerabilities and upload supported VEX documents for a project"),
VIEW_POLICY_VIOLATION("Provides the ability to view policy violations"),
VULNERABILITY_MANAGEMENT("Allows all management permissions of internally-defined vulnerabilities"),
VULNERABILITY_MANAGEMENT_CREATE("Allows creation of internally-defined vulnerabilities"),
VULNERABILITY_MANAGEMENT_READ("Allows reading internally-defined vulnerabilities"),
VULNERABILITY_MANAGEMENT_UPDATE("Allows updating internally-defined vulnerabilities and vulnerability tags"),
VULNERABILITY_MANAGEMENT_DELETE("Allows management of internally-defined vulnerabilities"),
POLICY_VIOLATION_ANALYSIS("Provides the ability to make analysis decisions on policy violations"),
ACCESS_MANAGEMENT("Allows the management of users, teams, and API keys"),
ACCESS_MANAGEMENT_CREATE("Allows create permissions of users, teams, and API keys"),
ACCESS_MANAGEMENT_READ("Allows read permissions of users, teams, and API keys"),
ACCESS_MANAGEMENT_UPDATE("Allows update permissions of users, teams, and API keys"),
ACCESS_MANAGEMENT_DELETE("Allows delete permissions of users, teams, and API keys"),
SYSTEM_CONFIGURATION("Allows all access to configuration of the system including notifications, repositories, and email settings"),
SYSTEM_CONFIGURATION_CREATE("Allows creating configuration of the system including notifications, repositories, and email settings"),
SYSTEM_CONFIGURATION_READ("Allows reading the configuration of the system including notifications, repositories, and email settings"),
SYSTEM_CONFIGURATION_UPDATE("Allows updating the configuration of the system including notifications, repositories, and email settings"),
SYSTEM_CONFIGURATION_DELETE("Allows deleting the configuration of the system including notifications, repositories, and email settings"),
PROJECT_CREATION_UPLOAD("Provides the ability to optionally create project (if non-existent) on BOM or scan upload"),
POLICY_MANAGEMENT("Allows the creation, modification, and deletion of policy"),
POLICY_MANAGEMENT_CREATE("Allows the creation of a policy"),
POLICY_MANAGEMENT_READ("Allows reading of policies"),
POLICY_MANAGEMENT_UPDATE("Allows the modification of a policy"),
POLICY_MANAGEMENT_DELETE("Allows the deletion of a policy");
```

### Addressed Issue

Fixes [Issue 1406](https://github.com/DependencyTrack/hyades/issues/1406) 

### Additional Details

Implemented this change to be leveraged with the ACL as it continues to develop. Allowing more granular permission assignment would let admins assign various roles to users such as an owner, developer, or viewer having different levels of access to the same projects.

### Checklist

- [X] I have read and understand the [contributing guidelines]
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have updated the [migration changelog] accordingly
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation] accordingly

[contributing guidelines]: ../CONTRIBUTING.md#pull-requests
[documentation]: https://dependencytrack.github.io/hyades/latest/development/documentation/
[migration changelog]: https://dependencytrack.github.io/hyades/latest/development/database-migrations/

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for the PR @zprebosnyak-lm! There are a few test failures:

```
Error:  Failures: 
Error:    PermissionsTest.testPermissionEnums:41 expected:<12> but was:<35>
Error:    PermissionResourceTest.getAllPermissionsTest:67 expected:<12> but was:<35>
```

Also, could you please sign-off your commits so the DCO check passes? You can find instructions by clicking on the *Details* link next to the failing build check.

**Comment by zprebosnyak-lm** [comment]
@nscuro Thanks for pointing that out, both PRs commits are signed, linting, and tests are now passing.

**Comment by nscuro** [comment]
Thanks @zprebosnyak-lm, looks good to me!

Unfortunately we have another pending PR that conflicts with this one: https://github.com/DependencyTrack/hyades-apiserver/pull/785

Judging by the PR size alone, I think it makes sense to get that one merged first, and then resolve conflicts in you PR, rather than the other way around. The change in Swagger annotations makes the other PR a tad harder to deal with...

Not a pretty situation, and in worst case we can take care of resolving those conflicts for you. Does that sound alright?

**Comment by zprebosnyak-lm** [comment]
Hey @nscuro, yeah that sounds good. I'll watch for that to be merged, just curious is there a timeline for merging that PR?

**Comment by nscuro** [comment]
It only has a few minor remarks pending, I'm hoping to get it merged tomorrow.

**Comment by nscuro** [comment]
@zprebosnyak-lm The PR is merged now.

**Comment by zprebosnyak-lm** [comment]
@nscuro No worries! The conflicts should all be resolved now

**Comment by nscuro** [comment]
Build failure is fixed via #818. If you merge `main` once more it should build.

**Review by nscuro — APPROVED** [review]
Thanks! 🙌

**Pull request merged**
